package com.opmldb.data;
// Generated 16-jun-2013 0:12:03 by Hibernate Tools 3.2.4.GA



/**
 * Table generated by hbm2java
 */
public class Table  implements java.io.Serializable {


     private Integer id;
     private int newcol;

    

    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNewcol() {
        return this.newcol;
    }
    
    public void setNewcol(int newcol) {
        this.newcol = newcol;
    }




}


