package com.opmldb.data;
// Generated 16-jun-2013 0:12:03 by Hibernate Tools 3.2.4.GA



/**
 * Temp generated by hbm2java
 */
public class Temp  implements java.io.Serializable {


     private Integer id;

    

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


